language: python

branches:
  only:
    - master
    - stable

matrix:
  fast_finish: true
  include:
    - python: 2.7
      script: python setup.py flake8 && python setup.py test
    - python: 3.2
      script: python setup.py test
    - python: 3.3
      script: python setup.py test
    - python: 3.4
      script: python setup.py test
    - python: pypy
      script: python setup.py flake8 && python setup.py test
